-- QUERY: TODOS OS QUARTOS DE UMA DETERMINADA CATEGORIA EM UM DETERMINADO HOTEL --
SELECT * FROM DEC_QUARTO 
WHERE CATEGORIA_ID = 1 
AND HOTEL_ID = 1;
-- QUERY: TODOS OS QUARTOS DE UMA DETERMINADA CATEGORIA EM UM DETERMINADO HOTEL --


-- QUERY: TODAS AS RESERVAS DE UM DETERMINADO PERÍODO --
SELECT * FROM DEC_RESERVA 
WHERE CHECKIN >= '2015-12-01'
OR CHECKOUT <= '2015-12-05';
-- QUERY: TODAS AS RESERVAS DE UM DETERMINADO PERÍODO --